name: Manual ArcBox Execution with parameters
on:
  workflow_dispatch:
    inputs:
      githubBranch:
        description: "Repo branch where the scripts are located"
        required: true
        default: "test1"    
jobs:
  TerraformAnalyzerTool:
    runs-on: ubuntu-latest
    env:
      TFSecExcludeRules:
      ChecovExcludeRules: CKV2_AZURE_10
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.githubBranch }}
      - name: Install brew -> tfsec and checkov
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /home/runner/.bash_profile
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          sudo apt-get install build-essential
          brew install gcc
          brew reinstall gcc
          brew install tfsec
          brew install checkov
      - name: Validate Terraform Script
        run: |
          cd ./azure_jumpstart_arcbox/terraform
          tfsec -f json --exclude "$TFSecExcludeRules" | tee terraform-lint-tfsec-results.txt
          checkov  --directory . --skip-check "$ChecovExcludeRules" | tee terraform-lint-checov-results.txt
        continue-on-error: true
      - name: Upload Terraform tfsec Lint Results File
        uses: actions/upload-artifact@v3
        with:
          name: terraform-lint-tfsec-results.txt
          path: ./azure_jumpstart_arcbox/terraform/terraform-lint-tfsec-results.txt
      - name: Upload Terraform Checov Lint Results File
        uses: actions/upload-artifact@v3
        with:
          name: terraform-lint-checov-results.txt
          path: ./azure_jumpstart_arcbox/terraform/terraform-lint-checov-results.txt